# Generated by Django 3.2.18 on 2023-03-23 11:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySuppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('contact_name', models.CharField(blank=True, max_length=50)),
                ('contact', models.CharField(blank=True, max_length=15)),
                ('website', models.CharField(max_length=50)),
                ('supplier_mail', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.categorysuppliers')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('product', models.CharField(max_length=1000)),
                ('count', models.IntegerField(blank=True)),
                ('description', models.CharField(blank=True, max_length=2500)),
                ('photo', models.ImageField(blank=True, upload_to='exemple_photo')),
                ('status', models.CharField(choices=[('Принят в обработку', 'Принят в обработку'), ('Выполняется', 'Выполняется'), ('Завершен', 'Завершен')], default='Принята в обработку', max_length=20)),
                ('order_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('number', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=1000)),
                ('invoice', models.FileField(blank=True, upload_to='invoices')),
                ('Status', models.CharField(choices=[('Ожидание счёта', 'Ожидание счёта'), ('Ожидание доставки', 'Ожидание доставки'), ('Получено', 'Получено')], default=1, max_length=250)),
                ('Supplier', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sup_orders', related_query_name='sup_order', to='order.supplier')),
            ],
        ),
    ]
