# Generated by Django 3.2.18 on 2023-03-29 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_item_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
