# Generated by Django 3.2.18 on 2023-03-30 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_orderitem_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('date', models.DateField(default=datetime.date.today, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='date',
        ),
    ]
