# Generated by Django 3.2.18 on 2023-03-30 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20230330_1400'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
