# Generated by Django 3.2.18 on 2023-04-06 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_alter_orderitem_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Status',
            field=models.CharField(choices=[('Ожидание счёта', 'Ожидание счёта'), ('Ожидание оплаты', 'Оэидание оплаты'), ('Ожидание доставки', 'Ожидание доставки'), ('Получено', 'Получено')], default=1, max_length=250),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='Supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sup_ordersitems', related_query_name='sup_orderitem', to='order.supplier'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
    ]
