# Generated by Django 3.2.18 on 2023-04-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_auto_20230406_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Status',
            field=models.CharField(choices=[('Ожидание счёта', 'Ожидание счёта'), ('Ожидание оплаты', 'Ожидание оплаты'), ('Ожидание доставки', 'Ожидание доставки'), ('Получено', 'Получено')], default=1, max_length=250),
        ),
    ]
