# Generated by Django 3.2.18 on 2023-04-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice',
            field=models.FileField(null=True, upload_to='invoices'),
        ),
    ]
