# Generated by Django 3.2.18 on 2023-04-06 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_alter_order_invoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
