# Generated by Django 3.2.18 on 2023-04-06 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_auto_20230406_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='category',
        ),
        migrations.AddField(
            model_name='categorysuppliers',
            name='suppliers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.supplier'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
