# Generated by Django 3.2.18 on 2023-04-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_auto_20230406_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice',
            field=models.FileField(blank=True, default=1, upload_to='invoices'),
            preserve_default=False,
        ),
    ]
