# Generated by Django 3.2.18 on 2023-04-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_order_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(blank=True, choices=[('RUB', 'RUB'), ('BYN', 'BYN'), ('USD', 'USD'), ('EUR', 'EUR')], max_length=100, null=True),
        ),
    ]
