# Generated by Django 3.2.18 on 2023-06-05 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0034_alter_item_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('Stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.stock')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.item')),
            ],
        ),
    ]
