# Generated by Django 3.2.18 on 2023-06-08 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0036_alter_stockitem_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='Stock',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
