# Generated by Django 3.2.18 on 2023-06-08 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0037_auto_20230608_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.item'),
        ),
    ]
